CMMS3/Controllers/AccessManagerController.cs
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace CMMS3.Controllers
{
    public class AccessManagerController : Controller
    {
        private readonly RoleManager<IdentityRole> _roleManager;

        public AccessManagerController(RoleManager<IdentityRole> roleManager)
        {
            _roleManager = roleManager;
        }

        public IActionResult Index()
        {
            var roles = _roleManager.Roles.ToList();
            return View(roles);
        }

        [HttpGet]
        public IActionResult AddRole()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddRole(string name)
        {
            if (string.IsNullOrEmpty(name)) return NotFound();
            var role = new IdentityRole()
            {
                Name = name
            };
            var result = await _roleManager.CreateAsync(role);
            if (result.Succeeded) return RedirectToAction("Index");

            foreach (var error in result.Errors)
            {
                ModelState.AddModelError(string.Empty, error.Description);
            }

            return View(role);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteRole(string id)
        {
            if (string.IsNullOrEmpty(id)) return NotFound();
            var role = await _roleManager.FindByIdAsync(id);
            if (role == null) return NotFound();
            await _roleManager.DeleteAsync(role);

            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> EditRole(string id)
        {
            if (string.IsNullOrEmpty(id)) return NotFound();

            var role = await _roleManager.FindByIdAsync(id);

            if (role == null) return NotFound();

            return View(role);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditRole(string id, string name)
        {
            if (string.IsNullOrEmpty(id) || string.IsNullOrEmpty(name)) return NotFound();

            var role = await _roleManager.FindByIdAsync(id);
            if (role == null) return NotFound();
            role.Name = name;
            var result = await _roleManager.UpdateAsync(role);
            if (result.Succeeded) return RedirectToAction("Index");

            foreach (var error in result.Errors)
            {
                ModelState.AddModelError(string.Empty, error.Description);
            }

            return View(role);
        }
    }
}

CMMS3/Views/AccessManager/Index.cshtml
@model List<IdentityRole>
@{
    ViewData["Title"] = "Index";
}
<h1>Index</h1>

<a asp-controller="AccessManager" asp-action="AddRole" class="btn btn-primary">جدید</a>

@if (!Model.Any())
{
    <h1>مقامی یافت نشد</h1>
}
else
{
    for (int i = 0; i < Model.Count; i++)
    {
        <div class="card mt-2">
            <div class="card-body">
                Role Name : <b>@Model[i].Name</b>
            </div>
            <div class="card-footer">
                <form asp-controller="AccessManager" asp-action="DeleteRole" method="post" asp-route-id="@Model[i].Id">

                    <a asp-controller="AccessManager" asp-action="EditRole" asp-route-id="@Model[i].Id"
                       class="btn btn-primary">Edit</a>

                    <button type="submit" class="btn btn-danger">Delete</button>
                </form>
            </div>
        </div>
    }
}